Feat/164/json output
animo/siera-cli pull request #240
Opened 2022-12-14 13:17 UTC by morrieinmaas

closes #164

2022-12-14 13:18 UTC, morrieinmaas commented
needs #162 to be merged first

2022-12-14 14:39 UTC, blu3beri requested changes
bit difficult to review, but it does not matter that much.

The JSON logger MUST not collide with the verbosity logs and it should just be "log the normal ouput in a json format with a nice key/value, thats it.

Input:
`siera --json connection invite`
Output:
```json
{
  "invitation_url": "https://...=",
  "connection_id": "abcd...xyz"
}
```

2022-12-14 14:39 UTC, blu3beri commented on crates/logger/src/lib.rs
> +
Json should not be a log level. Outputting JSON should not collide with the existing verbosity logs.

2022-12-14 14:39 UTC, blu3beri commented on crates/logger/src/macros.rs
> +            println!($($arg)*);
It would be nice here if we format the data, so the user does not have to do this themselves.

2022-12-14 14:47 UTC, morrieinmaas commented
> bit difficult to review, but it does not matter that much.
> 
> The JSON logger MUST not collide with the verbosity logs and it should just be "log the normal ouput in a json format with a nice key/value, thats it.
> 
> Input: `siera --json connection invite` Output:
> 
> ```json
> {
>   "invitation_url": "https://...=",
>   "connection_id": "abcd...xyz"
> }
> ```

hmmm ok. Wouldn't it make sense to only log the json if json is passed? Was thinking that if only a json value is printed one can easily use siera in a context where you get sth that is json. So if you pipe the output somewhere or use its output to be read by some other program it can load that into whatever datastructure represents json in that lang without having to do any sort of cleaning. Or what is your opinion on this?

2022-12-14 14:49 UTC, morrieinmaas commented on crates/logger/src/macros.rs
> +            println!($($arg)*);
ah true. actually better to do this here. what I did now is pass a formatted data blob that is json to this macro by using the `pretty_stringify_obj` function

2022-12-14 15:16 UTC, blu3beri commented
> > bit difficult to review, but it does not matter that much.
> > The JSON logger MUST not collide with the verbosity logs and it should just be "log the normal ouput in a json format with a nice key/value, thats it.
> > Input: `siera --json connection invite` Output:
> > ```json
> > {
> >   "invitation_url": "https://...=",
> >   "connection_id": "abcd...xyz"
> > }
> > ```
> 
> hmmm ok. Wouldn't it make sense to only log the json if json is passed? Was thinking that if only a json value is printed one can easily use siera in a context where you get sth that is json. So if you pipe the output somewhere or use its output to be read by some other program it can load that into whatever datastructure represents json in that lang without having to do any sort of cleaning. Or what is your opinion on this?
> 
> So what's happening now is that `--json | -j` are mutually exclusive with other logging flags plus when using `-j` it only prints json and nothing else

I understand the point of only showing JSON, and it should not give the default log output, but it should not remove the verbosity logs if specified. 

So basically the normal logger should check the state and if it is json we can prettify it (also give it custom keys) and log it like JSOn instead of normal.

2022-12-14 15:21 UTC, morrieinmaas commented
> > > bit difficult to review, but it does not matter that much.
> > > The JSON logger MUST not collide with the verbosity logs and it should just be "log the normal ouput in a json format with a nice key/value, thats it.
> > > Input: `siera --json connection invite` Output:
> > > ```json
> > > {
> > >   "invitation_url": "https://...=",
> > >   "connection_id": "abcd...xyz"
> > > }
> > > ```
> > 
> > 
> > hmmm ok. Wouldn't it make sense to only log the json if json is passed? Was thinking that if only a json value is printed one can easily use siera in a context where you get sth that is json. So if you pipe the output somewhere or use its output to be read by some other program it can load that into whatever datastructure represents json in that lang without having to do any sort of cleaning. Or what is your opinion on this?
> > So what's happening now is that `--json | -j` are mutually exclusive with other logging flags plus when using `-j` it only prints json and nothing else
> 
> I understand the point of only showing JSON, and it should not give the default log output, but it should not remove the verbosity logs if specified.
> 
> So basically the normal logger should check the state and if it is json we can prettify it (also give it custom keys) and log it like JSOn instead of normal.

Ok I understand what you mean (I think). so then you'd get the normal logs according to verbosity wrapped in JSON and the result is under a key in there like 'result' or sth like that?

2022-12-14 15:38 UTC, blu3beri commented
> > > > bit difficult to review, but it does not matter that much.
> > > > The JSON logger MUST not collide with the verbosity logs and it should just be "log the normal ouput in a json format with a nice key/value, thats it.
> > > > Input: `siera --json connection invite` Output:
> > > > ```json
> > > > {
> > > >   "invitation_url": "https://...=",
> > > >   "connection_id": "abcd...xyz"
> > > > }
> > > > ```
> > > 
> > > 
> > > hmmm ok. Wouldn't it make sense to only log the json if json is passed? Was thinking that if only a json value is printed one can easily use siera in a context where you get sth that is json. So if you pipe the output somewhere or use its output to be read by some other program it can load that into whatever datastructure represents json in that lang without having to do any sort of cleaning. Or what is your opinion on this?
> > > So what's happening now is that `--json | -j` are mutually exclusive with other logging flags plus when using `-j` it only prints json and nothing else
> > 
> > 
> > I understand the point of only showing JSON, and it should not give the default log output, but it should not remove the verbosity logs if specified.
> > So basically the normal logger should check the state and if it is json we can prettify it (also give it custom keys) and log it like JSOn instead of normal.
> 
> Ok I understand what you mean (I think). so then you'd get the normal logs according to verbosity wrapped in JSON and the result is under a key in there like 'result' or sth like that?

No, just the normal logs like the invitation url is in json, the verbosity logs will always stay the same.

Just the output that we always log (with log!()) will be json.

2022-12-14 15:46 UTC, morrieinmaas commented
> > > > > bit difficult to review, but it does not matter that much.
> > > > > The JSON logger MUST not collide with the verbosity logs and it should just be "log the normal ouput in a json format with a nice key/value, thats it.
> > > > > Input: `siera --json connection invite` Output:
> > > > > ```json
> > > > > {
> > > > >   "invitation_url": "https://...=",
> > > > >   "connection_id": "abcd...xyz"
> > > > > }
> > > > > ```
> > > > 
> > > > 
> > > > hmmm ok. Wouldn't it make sense to only log the json if json is passed? Was thinking that if only a json value is printed one can easily use siera in a context where you get sth that is json. So if you pipe the output somewhere or use its output to be read by some other program it can load that into whatever datastructure represents json in that lang without having to do any sort of cleaning. Or what is your opinion on this?
> > > > So what's happening now is that `--json | -j` are mutually exclusive with other logging flags plus when using `-j` it only prints json and nothing else
> > > 
> > > 
> > > I understand the point of only showing JSON, and it should not give the default log output, but it should not remove the verbosity logs if specified.
> > > So basically the normal logger should check the state and if it is json we can prettify it (also give it custom keys) and log it like JSOn instead of normal.
> > 
> > 
> > Ok I understand what you mean (I think). so then you'd get the normal logs according to verbosity wrapped in JSON and the result is under a key in there like 'result' or sth like that?
> 
> No, just the normal logs like the invitation url is in json, the verbosity logs will always stay the same.
> 
> Just the output that we always log (with log!()) will be json.

Sorry if I'm being daft here. Then we still have the log output in there if doing json? then one would still need to filter somehow the verbosity stuff and separate that from the desired json?! I thought the point was to just get sth that is definitely JSON so it can just be used in unix pipe or some program?

2022-12-14 16:51 UTC, blu3beri commented
> > > > > > bit difficult to review, but it does not matter that much.
> 
> > > > > > The JSON logger MUST not collide with the verbosity logs and it should just be "log the normal ouput in a json format with a nice key/value, thats it.
> 
> > > > > > Input: `siera --json connection invite` Output:
> 
> > > > > > ```json
> 
> > > > > > {
> 
> > > > > >   "invitation_url": "https://...=",
> 
> > > > > >   "connection_id": "abcd...xyz"
> 
> > > > > > }
> 
> > > > > > ```
> 
> > > > > 
> 
> > > > > 
> 
> > > > > hmmm ok. Wouldn't it make sense to only log the json if json is passed? Was thinking that if only a json value is printed one can easily use siera in a context where you get sth that is json. So if you pipe the output somewhere or use its output to be read by some other program it can load that into whatever datastructure represents json in that lang without having to do any sort of cleaning. Or what is your opinion on this?
> 
> > > > > So what's happening now is that `--json | -j` are mutually exclusive with other logging flags plus when using `-j` it only prints json and nothing else
> 
> > > > 
> 
> > > > 
> 
> > > > I understand the point of only showing JSON, and it should not give the default log output, but it should not remove the verbosity logs if specified.
> 
> > > > So basically the normal logger should check the state and if it is json we can prettify it (also give it custom keys) and log it like JSOn instead of normal.
> 
> > > 
> 
> > > 
> 
> > > Ok I understand what you mean (I think). so then you'd get the normal logs according to verbosity wrapped in JSON and the result is under a key in there like 'result' or sth like that?
> 
> > 
> 
> > No, just the normal logs like the invitation url is in json, the verbosity logs will always stay the same.
> 
> > 
> 
> > Just the output that we always log (with log!()) will be json.
> 
> 
> 
> Sorry if I'm being daft here. Then we still have the log output in there if doing json? then one would still need to filter somehow the verbosity stuff and separate that from the desired json?! I thought the point was to just get sth that is definitely JSON so it can just be used in unix pipe or some program?

Well just don't have a verbosity flag :). The regular command just displays the "pipable" information. We also have a quiet flag, for stuff like this.

2022-12-14 17:08 UTC, morrieinmaas commented
> > > > > > > bit difficult to review, but it does not matter that much.
> > 
> > 
> > > > > > > The JSON logger MUST not collide with the verbosity logs and it should just be "log the normal ouput in a json format with a nice key/value, thats it.
> > 
> > 
> > > > > > > Input: `siera --json connection invite` Output:
> > 
> > 
> > > > > > >
> > 
> > 
> > > > > > > {
> > 
> > 
> > > > > > > "invitation_url": "https://...=",
> > 
> > 
> > > > > > > "connection_id": "abcd...xyz"
> > 
> > 
> > > > > > > }
> > 
> > 
> > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > hmmm ok. Wouldn't it make sense to only log the json if json is passed? Was thinking that if only a json value is printed one can easily use siera in a context where you get sth that is json. So if you pipe the output somewhere or use its output to be read by some other program it can load that into whatever datastructure represents json in that lang without having to do any sort of cleaning. Or what is your opinion on this?
> > 
> > 
> > > > > > So what's happening now is that `--json | -j` are mutually exclusive with other logging flags plus when using `-j` it only prints json and nothing else
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > I understand the point of only showing JSON, and it should not give the default log output, but it should not remove the verbosity logs if specified.
> > 
> > 
> > > > > So basically the normal logger should check the state and if it is json we can prettify it (also give it custom keys) and log it like JSOn instead of normal.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Ok I understand what you mean (I think). so then you'd get the normal logs according to verbosity wrapped in JSON and the result is under a key in there like 'result' or sth like that?
> > 
> > 
> > > 
> > 
> > 
> > > No, just the normal logs like the invitation url is in json, the verbosity logs will always stay the same.
> > 
> > 
> > > 
> > 
> > 
> > > Just the output that we always log (with log!()) will be json.
> > 
> > 
> > Sorry if I'm being daft here. Then we still have the log output in there if doing json? then one would still need to filter somehow the verbosity stuff and separate that from the desired json?! I thought the point was to just get sth that is definitely JSON so it can just be used in unix pipe or some program?
> 
> Well just don't have a verbosity flag :). The regular command just displays the "pipable" information. We also have a quiet flag, for stuff like this.

Alright I think where this is going. What about the loading spinner then? How do you imagine handling that. As in I'd assume this is a nice feature when not using this to pipe, but when using this for pipe that - if I'm not mistaken - will be part of the output (and undesired) when wanting json.

2022-12-14 17:12 UTC, blu3beri commented
> > > > > > > > bit difficult to review, but it does not matter that much.
> 
> > > 
> 
> > > 
> 
> > > > > > > > The JSON logger MUST not collide with the verbosity logs and it should just be "log the normal ouput in a json format with a nice key/value, thats it.
> 
> > > 
> 
> > > 
> 
> > > > > > > > Input: `siera --json connection invite` Output:
> 
> > > 
> 
> > > 
> 
> > > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > {
> 
> > > 
> 
> > > 
> 
> > > > > > > > "invitation_url": "https://...=",
> 
> > > 
> 
> > > 
> 
> > > > > > > > "connection_id": "abcd...xyz"
> 
> > > 
> 
> > > 
> 
> > > > > > > > }
> 
> > > 
> 
> > > 
> 
> > > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > hmmm ok. Wouldn't it make sense to only log the json if json is passed? Was thinking that if only a json value is printed one can easily use siera in a context where you get sth that is json. So if you pipe the output somewhere or use its output to be read by some other program it can load that into whatever datastructure represents json in that lang without having to do any sort of cleaning. Or what is your opinion on this?
> 
> > > 
> 
> > > 
> 
> > > > > > > So what's happening now is that `--json | -j` are mutually exclusive with other logging flags plus when using `-j` it only prints json and nothing else
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > I understand the point of only showing JSON, and it should not give the default log output, but it should not remove the verbosity logs if specified.
> 
> > > 
> 
> > > 
> 
> > > > > > So basically the normal logger should check the state and if it is json we can prettify it (also give it custom keys) and log it like JSOn instead of normal.
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > Ok I understand what you mean (I think). so then you'd get the normal logs according to verbosity wrapped in JSON and the result is under a key in there like 'result' or sth like that?
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > No, just the normal logs like the invitation url is in json, the verbosity logs will always stay the same.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Just the output that we always log (with log!()) will be json.
> 
> > > 
> 
> > > 
> 
> > > Sorry if I'm being daft here. Then we still have the log output in there if doing json? then one would still need to filter somehow the verbosity stuff and separate that from the desired json?! I thought the point was to just get sth that is definitely JSON so it can just be used in unix pipe or some program?
> 
> > 
> 
> > Well just don't have a verbosity flag :). The regular command just displays the "pipable" information. We also have a quiet flag, for stuff like this.
> 
> 
> 
> Alright I think where this is going. What about the loading spinner then? How do you imagine handling that. As in I'd assume this is a nice feature when not using this to pipe, but when using this for pipe that - if I'm not mistaken - will be part of the output (and undesired) when wanting json.

The loader is send to stderr as a convention within unix.

2022-12-14 17:13 UTC, morrieinmaas commented
> > > > > > > > > bit difficult to review, but it does not matter that much.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > The JSON logger MUST not collide with the verbosity logs and it should just be "log the normal ouput in a json format with a nice key/value, thats it.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > Input: `siera --json connection invite` Output:
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > {
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > "invitation_url": "https://...=",
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > "connection_id": "abcd...xyz"
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > }
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > hmmm ok. Wouldn't it make sense to only log the json if json is passed? Was thinking that if only a json value is printed one can easily use siera in a context where you get sth that is json. So if you pipe the output somewhere or use its output to be read by some other program it can load that into whatever datastructure represents json in that lang without having to do any sort of cleaning. Or what is your opinion on this?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > So what's happening now is that `--json | -j` are mutually exclusive with other logging flags plus when using `-j` it only prints json and nothing else
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > I understand the point of only showing JSON, and it should not give the default log output, but it should not remove the verbosity logs if specified.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > So basically the normal logger should check the state and if it is json we can prettify it (also give it custom keys) and log it like JSOn instead of normal.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > Ok I understand what you mean (I think). so then you'd get the normal logs according to verbosity wrapped in JSON and the result is under a key in there like 'result' or sth like that?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > No, just the normal logs like the invitation url is in json, the verbosity logs will always stay the same.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > Just the output that we always log (with log!()) will be json.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Sorry if I'm being daft here. Then we still have the log output in there if doing json? then one would still need to filter somehow the verbosity stuff and separate that from the desired json?! I thought the point was to just get sth that is definitely JSON so it can just be used in unix pipe or some program?
> > 
> > 
> > > 
> > 
> > 
> > > Well just don't have a verbosity flag :). The regular command just displays the "pipable" information. We also have a quiet flag, for stuff like this.
> > 
> > 
> > Alright I think where this is going. What about the loading spinner then? How do you imagine handling that. As in I'd assume this is a nice feature when not using this to pipe, but when using this for pipe that - if I'm not mistaken - will be part of the output (and undesired) when wanting json.
> 
> The loader is send to stderr as a convention within unix.

ahhh okayyyyy - thanks for clarifying.

2022-12-14 20:06 UTC, morrieinmaas commented
Alright, so changed to your suggestions ( if I got them coeectly). no printing JSON for by default for applicable. Quiet frankly, preferred the previous way (or a version of it) with the flag.

2022-12-15 10:40 UTC, blu3beri requested changes
I don't think you understood my point.

Normally we do not want JSON output and we just want it seperated by a new line, like with the connections(uuid \n invitationURL).

When we pass the `--json` flag, we want the following:

```json
{
  "connection_id": "foo-bar",
  "invitation_url": "https://..."
}
```

the default behaviour will not change, but it is just swapped with the JSOn logger.

2022-12-15 10:40 UTC, blu3beri commented on crates/cli/src/modules/credential.rs
> +    let loader: Loader = Loader::start(&LoaderVariant::default());
Typing is not required for the loader here, it is infered.

2022-12-15 10:40 UTC, blu3beri commented on crates/automations/src/automations/create_credential_definition.rs
> +        log_info!("{} the credential definition...", "Registering".cyan());
Why is all this switched now to the info level? any reason?

2022-12-15 10:42 UTC, morrieinmaas commented on crates/automations/src/automations/create_credential_definition.rs
> +        log_info!("{} the credential definition...", "Registering".cyan());
That's because - and I think I possibly still misunderstand what you had in mind - logging json by default to be pipeable without supplying a flag this would be in stdout when not supplying a flag which I thought was not desired.

2022-12-19 17:18 UTC, blu3beri requested changes
Quite interested if the macro works. Did you test it? Do you have some output I can see?

2022-12-19 17:18 UTC, blu3beri commented on crates/cli/src/cli.rs
>      pub verbose: usize,
Verbose does not conflict with `json`.

2022-12-19 17:18 UTC, blu3beri commented on crates/cli/src/modules/credential.rs
> +                log_info!("Successfully offered a credential. Credential exchange id: ",);
This log should not print the `credential exchange id: ` or we should print the cred ex id.

2022-12-19 17:18 UTC, blu3beri commented on crates/cli/src/modules/wallet.rs
> +        /// The key_type to be used ed25519 or bls12381g2
```suggestion
        /// The key_type to be used; e.g. ed25519 or bls12381g2
```

2022-12-19 17:18 UTC, blu3beri commented on crates/cli/src/modules/wallet.rs
> +                log_info!("Successfully created local DID: ",);
We should either print the did or do not end it with :.

2022-12-19 17:18 UTC, blu3beri commented on crates/cloudagent-python/src/cloudagent/json_ld.rs
> +use crate::agent::CloudAgentPython;
This should not be here.

2022-12-19 17:18 UTC, blu3beri commented on crates/logger/src/lib.rs
> +    pub should_json: bool,
```suggestion
    pub should_output_json: bool,
```

2022-12-19 17:18 UTC, blu3beri commented on crates/logger/src/lib.rs
> +        should_json: bool,
```suggestion
        should_output_json: bool,
```

You get it.

2022-12-19 17:18 UTC, blu3beri commented on crates/logger/src/macros.rs
> +        if ::siera_logger::STATE.read().unwrap().should_json {
Since this uses `println` we should also check the loglevel that it is not `Off`.

2022-12-19 17:19 UTC, morrieinmaas commented
cheers. Thanks for all the feedback. Will address asap

2022-12-19 17:27 UTC, morrieinmaas commented
@blu3beri addressed

2022-12-19 18:36 UTC, blu3beri commented on crates/cli/src/modules/wallet.rs
> +                log_info!("Successfully created local DID: {:?}", response.did);
I don't think we need debug printing for the did (I assume it is a string). If it is not a string we need to convert it.

2022-12-19 18:37 UTC, blu3beri reviewed
One more comment.

2022-12-20 07:11 UTC, TimoGlastra commented
I'm with @morrieinmaas here. I think it's quite normal for CLIs / tools that when you enable json mode, ALL messages will be printed in json. This way you can parse the logs and make sense of it (structured logging). If you enable verbosity logs, these should also be logged as json imho.

Some examples:
- https://logger.tsed.io/layouts/json.html#example
- https://tslog.js.org/#/?id=type-pretty-json-hidden


for example tsed has the following structure: 

```
{"startTime":"2017-06-05T22:23:08.479Z","categoryName":"json-test","data":["this is just a test"],"level":"INFO","context":{}},
{"startTime":"2017-06-05T22:23:08.483Z","categoryName":"json-test","data":["of a custom appender"],"level":"ERROR","context":{}},
{"startTime":"2017-06-05T22:23:08.483Z","categoryName":"json-test","data":["that outputs json"],"level""WARN","context":{}},
```

Also leaving this: https://stackify.com/what-is-structured-logging-and-why-developers-need-it/

2022-12-20 08:06 UTC, blu3beri commented
> I'm with @morrieinmaas here. I think it's quite normal for CLIs / tools that when you enable json mode, ALL messages will be printed in json. This way you can parse the logs and make sense of it (structured logging). If you enable verbosity logs, these should also be logged as json imho.
> 
> 
> 
> Some examples:
> 
> - https://logger.tsed.io/layouts/json.html#example
> 
> - https://tslog.js.org/#/?id=type-pretty-json-hidden
> 
> 
> 
> 
> 
> for example tsed has the following structure: 
> 
> 
> 
> ```
> 
> {"startTime":"2017-06-05T22:23:08.479Z","categoryName":"json-test","data":["this is just a test"],"level":"INFO","context":{}},
> 
> {"startTime":"2017-06-05T22:23:08.483Z","categoryName":"json-test","data":["of a custom appender"],"level":"ERROR","context":{}},
> 
> {"startTime":"2017-06-05T22:23:08.483Z","categoryName":"json-test","data":["that outputs json"],"level""WARN","context":{}},
> 
> ```
> 
> 
> 
> Also leaving this: https://stackify.com/what-is-structured-logging-and-why-developers-need-it/

Yes, makes sense. I am not opposed to json verbosity logging, but my point was mainly that logging JSON should mute the verbosity logs. I think we can address this in a separate PR as it would require reworking the whole logger. We would probably need to always pass a json / struct and create a normal message from that or log it as JSON.

2022-12-20 09:46 UTC, morrieinmaas commented
> > I'm with @morrieinmaas here. I think it's quite normal for CLIs / tools that when you enable json mode, ALL messages will be printed in json. This way you can parse the logs and make sense of it (structured logging). If you enable verbosity logs, these should also be logged as json imho.
> > Some examples:
> > 
> > * https://logger.tsed.io/layouts/json.html#example
> > * https://tslog.js.org/#/?id=type-pretty-json-hidden
> > 
> > for example tsed has the following structure:
> > ```
> > 
> > {"startTime":"2017-06-05T22:23:08.479Z","categoryName":"json-test","data":["this is just a test"],"level":"INFO","context":{}},
> > 
> > {"startTime":"2017-06-05T22:23:08.483Z","categoryName":"json-test","data":["of a custom appender"],"level":"ERROR","context":{}},
> > 
> > {"startTime":"2017-06-05T22:23:08.483Z","categoryName":"json-test","data":["that outputs json"],"level""WARN","context":{}},
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also leaving this: https://stackify.com/what-is-structured-logging-and-why-developers-need-it/
> 
> Yes, makes sense. I am not opposed to json verbosity logging, but my point was mainly that logging JSON must not mute the verbosity logs. I think we can address this in a separate PR as it would require reworking the whole logger. We would probably need to always pass a json / struct and create a normal message from that or log it as JSON.

Or not pass json/struct and create json/struct on the fly with eg a timestamp if the/a key is missing but value is present.

I'll have a look into how this can be 'formally' handled as in sticking to some convention

2023-03-10 08:06 UTC, blu3beri commented
@morrieinmaas what is the status of this PR?

2023-03-12 20:59 UTC, closed without merging