feat: json logger
animo/siera-cli pull request #252
Opened 2023-03-10 14:37 UTC by blu3beri

2023-03-31 08:45 UTC, morrieinmaas commented on crates/logger/src/lib.rs
> +    pub should_final_copy: bool,
maybe `should_copy_clip`?

2023-03-31 08:49 UTC, blu3beri commented on crates/logger/src/lib.rs
> +    pub should_final_copy: bool,
As in "should copy to clipboard?"

I added `final` here to indicate that the final log, i.e. the value you would like to copy (invite, connection id, etc.) would be copied. 

I don't think that `should_copy_clipboard` or `should_final_copy` are good. I will have a think.

2023-03-31 08:53 UTC, morrieinmaas commented on crates/logger/src/macros.rs
>  #[macro_export]
I'm not sure that's possible but all the logger macros are basically the same match passing different `::siera_logger::LogLevel::Warn` and taking a different namespace. maybe this could be a generated by a macro (so macro from macro)? but I guess that's shooting pigeons with tanks really and makes this more complicated than it needs to be.

2023-03-31 08:55 UTC, morrieinmaas commented on crates/cli/src/register.rs
> +        debug!({
this new syntax with the JSON parsing is way nicer!

2023-03-31 08:57 UTC, blu3beri commented on crates/logger/src/macros.rs
>  #[macro_export]
Thats some macro meta right there. I think it is a cool idea, but yes it feels like shooting pigeons with tanks. If you are interested in macros, feel free to try it.

2023-03-31 09:00 UTC, morrieinmaas commented on crates/logger/src/lib.rs
> +    pub should_final_copy: bool,
I mena it's not world changing especially from a user perspective. But yeah let's name it sth more eaningful then `should_final_copy` - found that a bit confusing. Otherwise really great changes

2023-03-31 09:12 UTC, morrieinmaas commented on crates/cli/src/cli.rs
> +    #[clap(long = "json", short = 'j', help = "TODO")]
maybe we can add the TODO here?

2023-03-31 09:23 UTC, blu3beri commented on crates/cli/src/cli.rs
> +    #[clap(long = "json", short = 'j', help = "TODO")]
Good catch. fixed it.

2023-03-31 09:38 UTC, morrieinmaas commented on crates/cli/src/help_strings.rs
> +            Self::OutputJson => "Output format will je JSON",
```suggestion
            Self::OutputJson => "Output format will be JSON",
```

2023-03-31 09:38 UTC, morrieinmaas commented on crates/cli/src/modules/automation.rs
> +                                connection.id.bold()
can this move into the {}?

2023-03-31 09:39 UTC, morrieinmaas requested changes
Left some more Qs/nit picks

2023-03-31 10:03 UTC, blu3beri commented
Fixed your comments. can I merged it?

2023-04-06 08:40 UTC, morrieinmaas approved these changes
LGTM, @blu3beri !

2023-04-28 11:43 UTC, merged